import './globals.scss'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Box } from '@mui/system'
import WaterMark from '@/ui/components/WaterMark/WaterMark'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <html lang="en">
      <body className={inter.className}>

        <Box className={`td-relative`}>
          <WaterMark/>
          <Box>

          </Box>
          <Box className={`td-relative`}>{children}</Box>

        </Box>
      </body>
    </html>
  )
}
