version: '3.8'

services:
  create_certs:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    container_name: create_certs
    command: >
      bash -c '
      find ./ -type f -print;


        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --ca-cert=./config/certificates/certs/ca/ca.crt --ca-key=./config/certificates/certs/ca/ca.key --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs;
        fi;
        chown -R 1000:0 /certs;
      '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes:
      - certs:/certs
      - .:/usr/share/elasticsearch/config/certificates
    networks:
      - elastic
    ports:
      - 80:80
      - 443:443

volumes:
  certs:
    driver: local

networks:
  elastic:
    driver: bridge